### ISSUE TITLE
Add Hoefler & Co proof texts

### ISSUE THREAD

**Issue by simoncozens** [silnrsi/fontproof#14]
Jonathan has just open-sourced his (Latin) proof texts: https://github.com/hoeflerco/proofs

They should be added as a proofing command.

**Comment by jvgaultney** [comment]
Jonathan has licensed the text via cc-by-nc-sa, which means we can't use it. I've seen his thread on this, but whatever his intent, nc would place a restriction on fontproof. So sorry, can't do unless his drops the nc.

**Comment by simoncozens** [comment]
Darn. Oh well. :-)
