### ISSUE TITLE
SSL handshake issue with external website called by \pi

### ISSUE THREAD

**Issue by n7s** [silnrsi/fontproof#16]
Looks like the ssl connection to the external website providing the pi numbers is not happy: 

"Could not read pi from https://uploadbeta.com/api/pi/?n=104: sslv3 alert handshake failure at proof.sil:17:1: in \pitable: 0x559697c9db20"

**Comment by n7s** [comment]
@devosb Thanks for the fix in b339a3c, I can confirm that it works. Now we just need a release, an update of sile-packages to point to that relase and then packagemanager with the vagrant profile and CI use can be updated.

**Comment by alerque** [comment]
@n7s Have you guys started using the official PPA for SILE yet or are you still using an internal one?

**Comment by n7s** [comment]
We are now using your own packaging work in the official sile PPA, thanks btw. (With "sile-packages" I mean the catalog for the sile packagemanager.).

**Comment by n7s** [comment]
and if I am not clear enough: we now install fontproof via sile -e 'installPackage("fontproof").

**Comment by devosb** [comment]
FWIW, I did not get the SSL handshake error when running locally (Ubuntu focal, I don't remember if it worked on Ubuntu bionic or not). So there may not have been an issue with FontProof. Anyway, the new code does not require Internet access at all, so the whole issue goes away.
